# directories
path_dir_data: 'data'
path_dir_data_raw: 'data_raw'
path_dir_data_processed: 'data_processed'
path_dir_pylcaio: 'data_pylcaio'
path_dir_pymrio: 'data_pymrio'
path_dir_e2m: 'data_e2m'
path_dir_processing_logs: 'logs'
# databases
ecoinvent_version_name: 'ecoinvent_3.5_cutoff_ecoSpold02'
exiobase: 'exiobase_monetary_pxp/IOT_2012_pxp.zip'
# filenames
# pylcaio
pylcaio_class_instance_before_hybrid: 'pylcaio_class_instance_before_hybrid.pkl'
pylcaio_class_instance_after_hybrid: 'pylcaio_class_instance_after_hybrid.pkl'
pylcaio_database_loader_class_instance: 'pylcaio_database_loader_class_instance.pkl'
# pymrio
pymrio_class_instance: 'pymrio_class_instance.pkl'
# ecospold2matrix ("e2m")
e2m_pickle_filename: 'Pandas_symmNorm.gz.pickle'
# packages
path_dir_repo_pylcaio: 'github/pylcaio/src'
# json files
path_dict_io_countries_per_lca_region: 'bw2hybrid/data/dict_io_countries_per_lca_region.json'
path_dict_io_countries_list_per_lca_region: 'bw2hybrid/data/dict_io_countries_list_per_lca_region.json'
path_list_io_countries_and_regions: 'bw2hybrid/data/list_io_countries_and_regions.json'
path_list_io_countries: 'bw2hybrid/data/list_io_countries.json'
path_list_electricity_prices: 'bw2hybrid/data/electricity_prices.csv'