# directories
path_dir_data: 'data'
path_dir_databases: 'data_pylcaio_input'
path_dir_pylcaio: 'data_pylcaio'
path_dir_pymrio: 'data_pymrio'
path_dir_e2m: 'data_e2m'
# databases
ecoinvent: 'ecoinvent-3.5-cutoff'
exiobase: 'exiobase_monetary_pxp/IOT_2012_pxp.zip'
# filenames
# pylcaio
pylcaio_class_instance_before_hybrid: 'pylcaio_class_instance_before_hybrid.pkl'
pylcaio_class_instance_after_hybrid: 'pylcaio_class_instance_after_hybrid.pkl'
pylcaio_database_loader_class_instance: 'pylcaio_database_loader_class_instance.pkl'
# pymrio
pymrio_class_instance: 'pymrio_class_instance.pkl'
# packages
pylcaio: 'github/pylcaio/src'